apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: ShengrossGitOpsACRcicd.azurecr.io/azvote/azure-vote-front
    newTag: 1f7b949d0043f213334c7320389c19a4d42a3bdc
  - name: ShengrossGitOpsACRcicd.azurecr.io/azvote/azure-vote-back
    newTag: 1f7b949d0043f213334c7320389c19a4d42a3bdc
resources:
  - manifests.yaml